package:
  name: carculator
  version: {{ environ['VERSION'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  script_env:
    - VERSION
    - CONDA_BLD_PATH

requirements:
  build:
    - python
    - setuptools
  run:
    - carculator_utils

test:
  imports:
    - carculator

about:
  home: https://github.com/romainsacchi/carculator
  license: BSD License
  summary: 'Life Cycle Assessment for passenger cars.'
license_family: BSD
